# Generated by Django 5.2.16 on 2026-07-08 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('organizacao', models.CharField(blank=True, max_length=255)),
                ('departamento', models.CharField(choices=[('Recursos Humanos', 'Recursos Humanos'), ('Tecnologia de Informação', 'Tecnologia de Informação'), ('Finanças', 'Finanças'), ('Operações', 'Operações'), ('Saúde Pública', 'Saúde Pública'), ('Marketing', 'Marketing'), ('Vendas', 'Vendas'), ('Outro', 'Outro')], default='Outro', max_length=100)),
                ('local', models.CharField(blank=True, max_length=255)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Remoto', 'Remoto'), ('Híbrido', 'Híbrido')], default='Presencial', max_length=50)),
                ('nivel_formacao', models.CharField(blank=True, max_length=100)),
                ('anos_experiencia_min', models.PositiveIntegerField(default=0)),
                ('tipo_contrato', models.CharField(choices=[('Tempo Inteiro', 'Tempo Inteiro'), ('Tempo Parcial', 'Tempo Parcial'), ('Consultoria', 'Consultoria'), ('Estágio', 'Estágio')], default='Tempo Inteiro', max_length=100)),
                ('salario', models.CharField(blank=True, max_length=100)),
                ('prazo_candidatura', models.CharField(blank=True, max_length=100)),
                ('competencias_requeridas', models.JSONField(default=list)),
                ('responsabilidades', models.JSONField(default=list)),
                ('descricao', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Suspensa', 'Suspensa')], default='Aberta', max_length=50)),
                ('tor_file_path', models.CharField(blank=True, max_length=500)),
                ('origem', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='accounts.organisation')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
    ]
