# Generated by Django 6.0.7 on 2026-07-10 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewGuideSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('texto_gerado', models.TextField()),
                ('texto_editado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('submetido', 'Submetido pelo Júri'), ('aprovado', 'Aprovado')], default='pendente', max_length=20)),
                ('chair_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiao_sessions', to='vagas.vaga')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
