# Generated by Django 6.0.7 on 2026-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_interview_guide_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tor_aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
