# Generated by Django 6.0.7 on 2026-08-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_vaga_avaliacao_encerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='numero_vagas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaga',
            name='prazo_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
