# Generated by Django 6.0.7 on 2026-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_vaga_numero_vagas_vaga_prazo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='notificacoes_enviadas',
            field=models.BooleanField(default=False),
        ),
    ]
