# Generated by Django 6.0.7 on 2026-09-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_add_notificacoes_enviadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='modo_rapido',
            field=models.BooleanField(default=False),
        ),
    ]
