# Generated by Django 6.0.7 on 2026-09-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_add_modo_rapido_to_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tor_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
