# Generated by Django 6.0.7 on 2026-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0011_add_tor_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='criterios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
