# Generated by Django 6.0.7 on 2026-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0012_vaga_criterios'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='ultimo_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
