from django.urls import path
from . import views

urlpatterns = [
    path("", views.vaga_list, name="vaga_list"),
    path("criar/", views.vaga_create, name="vaga_create"),
    path("<uuid:pk>/", views.vaga_detail, name="vaga_detail"),
    path("<uuid:pk>/editar/", views.vaga_edit, name="vaga_edit"),
    path("<uuid:pk>/confirmar-analise/", views.vaga_confirmar_analise, name="vaga_confirmar_analise"),
    path("<uuid:pk>/aprovar-tor/", views.vaga_aprovar_tor, name="vaga_aprovar_tor"),
    path("<uuid:pk>/eliminar/", views.vaga_delete, name="vaga_delete"),
    path("parse-tor/", views.parse_tor_view, name="parse_tor"),
    path("analyse-tor/", views.analyse_tor_view, name="analyse_tor"),
    path("<uuid:pk>/perguntas-entrevista/", views.gerar_perguntas_entrevista, name="gerar_perguntas"),
    path("<uuid:pk>/perguntas-entrevista/download/", views.download_perguntas, name="download_perguntas"),
    path("<uuid:pk>/enviar-juri/", views.enviar_guiao_juri, name="enviar_guiao_juri"),
    path("<uuid:pk>/guiao/<uuid:session_id>/aprovar/", views.guiao_aprovar, name="guiao_aprovar"),
    path("<uuid:pk>/guiao/<uuid:session_id>/download/", views.guiao_download, name="guiao_download"),
    path("juri/<uuid:token>/", views.guiao_juri_view, name="guiao_juri"),
    path("<uuid:pk>/comite/adicionar/", views.comite_adicionar_avaliador, name="comite_adicionar_avaliador"),
    path("comite/<uuid:token>/", views.comite_avaliacao_view, name="comite_avaliacao"),
    path("<uuid:pk>/comite/confirmar/", views.comite_confirmar_decisoes, name="comite_confirmar_decisoes"),
    path("<uuid:pk>/comite/<uuid:session_pk>/remover/", views.comite_remover_avaliador, name="comite_remover_avaliador"),
    path("<uuid:pk>/comite/<uuid:session_pk>/repor/", views.comite_repor_avaliacao, name="comite_repor_avaliacao"),
    path("<uuid:pk>/comite/resultados/", views.comite_resultados, name="comite_resultados"),
    path("<uuid:pk>/candidato/<uuid:candidato_pk>/decisao/", views.candidato_decisao_final, name="candidato_decisao_final"),
    path("<uuid:pk>/enviar-avaliacao-grupo/", views.enviar_avaliacao_grupo, name="enviar_avaliacao_grupo"),
    path("avaliacao-grupo/<uuid:token>/", views.avaliacao_grupo_juri, name="avaliacao_grupo_juri"),
    path("<uuid:pk>/confirmar-avaliacoes/", views.confirmar_avaliacoes_grupo, name="confirmar_avaliacoes_grupo"),
    path("<uuid:pk>/shortlist/", views.shortlist, name="shortlist"),
    path("<uuid:pk>/shortlist/<uuid:candidato_pk>/entrevista/", views.mover_para_entrevista, name="mover_para_entrevista"),
    path("<uuid:pk>/relatorio/", views.relatorio_selecao, name="relatorio_selecao"),
    path("<uuid:pk>/relatorio/download/", views.relatorio_selecao_download, name="relatorio_selecao_download"),
]
