# Generated by Django 5.2.16 on 2026-07-08 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vagas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('experiencia_anos', models.PositiveIntegerField(default=0)),
                ('competencias', models.JSONField(default=list)),
                ('formacao', models.JSONField(default=list)),
                ('idiomas', models.JSONField(default=list)),
                ('resumo', models.TextField(blank=True)),
                ('etapa', models.CharField(choices=[('Candidatura Recebida', 'Candidatura Recebida'), ('Em Triagem', 'Em Triagem'), ('Entrevista', 'Entrevista'), ('Proposta', 'Proposta'), ('Contratado', 'Contratado'), ('Rejeitado', 'Rejeitado')], default='Candidatura Recebida', max_length=100)),
                ('score_fit', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('cv_file_path', models.CharField(blank=True, max_length=500)),
                ('perfil_completo', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos_criados', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='accounts.organisation')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.vaga')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
    ]
