# Generated by Django 6.0.7 on 2026-07-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatos', to='vagas.vaga'),
        ),
    ]
