# Generated by Django 6.0.7 on 2026-07-10 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_candidato_vaga'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_entrevista', models.DateField(blank=True, null=True)),
                ('pontuacao', models.PositiveSmallIntegerField(blank=True, help_text='1–5', null=True)),
                ('recomendacao', models.CharField(blank=True, choices=[('recomendado', 'Recomendado'), ('a_considerar', 'A considerar'), ('nao_recomendado', 'Não recomendado')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('pontos_fortes', models.TextField(blank=True)),
                ('pontos_fracos', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_entrevista', to='candidatos.candidato')),
            ],
        ),
    ]
