# Generated by Django 6.0.7 on 2026-07-10 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_nota_entrevista'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('submetida', 'Submetida pelo Júri'), ('confirmada', 'Confirmada por HR')], default='pendente', max_length=20)),
                ('pontuacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recomendacao', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('pontos_fortes', models.TextField(blank=True)),
                ('pontos_fracos', models.TextField(blank=True)),
                ('data_entrevista', models.DateField(blank=True, null=True)),
                ('chair_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_sessions', to='candidatos.candidato')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
