# Generated by Django 6.0.7 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_avaliacao_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaosession',
            name='respostas_perguntas',
            field=models.JSONField(default=list),
        ),
    ]
