# Generated by Django 6.0.7 on 2026-08-01 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_respostas_perguntas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='motivo_rejeicao',
            field=models.CharField(blank=True, choices=[('perfil_inadequado', 'Perfil não adequado ao cargo'), ('experiencia_insuficiente', 'Experiência insuficiente'), ('formacao_insuficiente', 'Formação abaixo do requisito'), ('melhor_candidato', 'Outro candidato mais adequado seleccionado'), ('candidato_desistiu', 'Candidato desistiu do processo'), ('outro', 'Outro motivo')], max_length=50),
        ),
        migrations.CreateModel(
            name='CandidatoNota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_log', to='candidatos.candidato')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
