# Generated by Django 6.0.7 on 2026-08-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_candidato_motivo_rejeicao_candidatonota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='etapa',
            field=models.CharField(choices=[('Candidatura Recebida', 'Candidatura Recebida'), ('Em Triagem', 'Em Triagem'), ('Pré-Seleccionado', 'Pré-Seleccionado'), ('Entrevista', 'Entrevista'), ('Proposta', 'Proposta'), ('Contratado', 'Contratado'), ('Rejeitado', 'Rejeitado')], default='Candidatura Recebida', max_length=100),
        ),
    ]
