# Generated by Django 6.0.7 on 2026-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_candidato_etapa_add_pre_seleccionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cv_texto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
