# Generated by Django 6.0.7 on 2026-09-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_candidato_cv_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='avaliacao_criterios',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
